### ISSUE TITLE
Scrolls to top on #hash change

### ISSUE THREAD

**Issue by zackify** [taion/react-router-scroll#10]
Take out the plugin, link to an id on the page, it works. Add this back, it will scroll up instead of to the id. I'll look into it myself but I wanted to post this so it's known first.

**Comment by taion** [comment]
Just return `false` from `shouldUpdateScroll` if only `hash` changes. Note per https://github.com/taion/scroll-behavior/issues/22 that there's no handling for navigating to a different route with a hash.

**Comment by zackify** [comment]
Okay got it.

**Comment by f0rr0** [comment]
@taion https://github.com/taion/react-router-scroll/issues/10#issuecomment-218496265
The back button will not work for same page hash anchors in that case

**Comment by f0rr0** [comment]
@taion How would the back button work for same page hash anchors in that case?

**Comment by taion** [comment]
It wouldn't, unfortunately.
