### ISSUE TITLE
Can we scroll some other element instead of Window?

### ISSUE THREAD

**Issue by Brendan-csel** [taion/react-router-scroll#12]
Sorry if I've missed this somewhere.  Our page layout has a fixed sidebar and content section.  The content element contains the page content and this is the element that scrolls.  

Can I define the scroll container element  to be something other than "window"?

**Comment by Aweary** [comment]
`react-router-scroll` uses https://github.com/taion/scroll-behavior for managing scroll state. If anything you should open an issue there.

**Comment by taion** [comment]
Yeah... I want to add support for this but I haven't had time yet.

**Comment by Brendan-csel** [comment]
I've opened another issue here: https://github.com/taion/scroll-behavior/issues/75
