### ISSUE TITLE
Perform the scroll operation ourselves so that we can smooth scroll

### ISSUE THREAD

**Issue by satazor** [taion/react-router-scroll#15]
Hello,

First of all I don't know if this is the right repository to create this issue or if `scroll-behaviour` was the right one, but since I'm using react-router-scroll I've decided to start the thread here.

As you might know, there's a native API to perform smooth scrolling, with a [polyfil](https://github.com/iamdustan/smoothscroll/blob/master/smoothscroll.js) for older browsers.
See: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior and https://drafts.csswg.org/cssom-view/#dictdef-scrolltooptions

At the moment, this library uses `scrollTo(x, y)` but I would like to use `scrollTo({ left: x, top: y, behavior: 'smooth' })`. `react-router-scroll` and `scroll-behavior` could accept an option (e.g.: `updateScrollPos`) which is a function that receives the x and y values and its role is to update the scroll position. Its default value would be the current behavior.

Thoughts?

**Comment by satazor** [comment]
I've made a workaround by monkey matching `window.scrollTo` so that I could do my own updateScrollPos function:

```js
import 'smoothscroll-polyfill';
import wrap from 'lodash/wrap';

const stretcherEl = document.createElement('div');
let timeout;

window.scrollTo = wrap(window.scrollTo, (scrollTo, x, y) => {
    stretcherEl.style.height = `${document.body.scrollHeight}px`;
    document.body.appendChild(stretcherEl);

    if (timeout) {
        clearTimeout(timeout);
        timeout = null;
    }

    if (typeof x === 'number' && typeof y === 'number') {
        scrollTo({ left: x, top: y, behavior: 'smooth' });
        timeout = setTimeout(() => {
            timeout = null;
            document.body.removeChild(stretcherEl);
        }, 1000);
    } else {
        document.body.removeChild(stretcherEl);
        scrollTo(x);
    }
});
```

This is being used in conjunction with an `opacity` transition between pages, so I need to keep the height of the body intact to prevent weird scroll snaps.

**Comment by taion** [comment]
This would be done in the scroll-behavior layer. I'd be happy to look at a PR to make that pluggable.

**Comment by slashwhatever** [comment]
Did this get pluggable? How do we implement?

**Comment by taion** [comment]
Send a PR to scroll-behavior exposing a hook for setting the scroll callback.
