### ISSUE TITLE
integration with react-router-relay

### ISSUE THREAD

**Issue by tomconroy** [taion/react-router-scroll#20]
Is it possible to scroll only *after* relay has finished loading?

I can get it to work but it's a hack:

```
useScroll((prevRouterProps, props) => {
  if (!props.queryAggregator.readyState.done) {
    return false;
  }
  return true;
})

...
   
const render = ({ done }) => {
  if (done) {
    if (typeof window !== 'undefined') {
      window.scrollTo(0, 0);
    }
  }
}

...
<Route ... render={render} />
```

**Comment by taion** [comment]
Not in this library – it'd have to be a separate library that adds a router middleware that uses the underlying `ScrollBehavior` and hooks into the Relay lifecycle stuff.

This is not currently a priority for me – we show loading indicators whenever we're waiting on Relay data, so we're fine with scroll position updating immediately.

**Comment by tomconroy** [comment]
Thanks for the fast reply! Makes sense.
