### ISSUE TITLE
Ability to scroll a target div instead of window

### ISSUE THREAD

**Issue by ro-savage** [taion/react-router-scroll#21]
Our application is a fixed size, with an internal div using overflow: scroll.

This means we aren't able to scroll to top, as the current implementation of `scroll-behavior` assumes you are scrolling the window.

I have created a modified version where you are able to pass a `target id` through to `scroll-behavior` and instead scroll the target.

It is a pretty rough implementation. We are targeting an id with `getElementById` as its faster, however it could easily be changed to use `querySelector` and allow targeting by anything.

Just wondering if this would be useful to others? And their opinions on the best way to go about it.

You can have a look the hacky way I implemented on [this gist](https://gist.github.com/ro-savage/2ee466eba354b114fb7f33ebddc2c8d1).

(Main changes are Lines 107-114 and 172-179 of scroll-behavior.js)

**Comment by taion** [comment]
This is a known missing feature.

**Comment by ro-savage** [comment]
This implementation is obviously basic, other things that would be needed to be more robust.

- [x] Allowing a target to scroll instead of window
- [ ] Remember previous scroll position of div, when pressing 'back'
- [ ] Handling multiple divs that scroll independently

Is there anything else?

**Comment by taion** [comment]
No – the idea would be to allow arbitrary numbers of scroll-managed elements. See react-router-restore-scroll for an example.

**Comment by jwheeler-gs** [comment]
Any progress on this enhancement? This feature would be useful for me as well.

**Comment by Mesoptier** [comment]
Have a look at this PR: https://github.com/taion/react-router-scroll/pull/27

**Comment by taion** [comment]
Closed by #27, #29.

**Comment by taion** [comment]
And released in v0.3.0.
