### ISSUE TITLE
'warning' in devDependencies but used in production

### ISSUE THREAD

**Issue by PhilWaldmann** [taion/react-router-scroll#31]
[ScrollContainer.js](https://github.com/taion/react-router-scroll/blob/master/src/ScrollContainer.js) imports the `warning` package, but it's only listed in `devDependencies`.

This will break production builds!

**Comment by taion** [comment]
Technically it's never "used" in production because of the dev-expression plugin, but yeah it does get required.

**Comment by taion** [comment]
:p

**Comment by PhilWaldmann** [comment]
👍  Thx

**Comment by taion** [comment]
Released in v0.3.1
