### ISSUE TITLE
Uncaught ReferenceError: __DEV__ is not defined

### ISSUE THREAD

**Issue by momirov** [taion/react-router-scroll#34]
``__DEV__`` is used in development, should I pollute my webpack config with this or check can be added?

**Comment by taion** [comment]
Neither. I forgot the Babel transform.

**Comment by taion** [comment]
Fixed by #35

**Comment by momirov** [comment]
@taion thanks for a quick fix, appreciate it

**Comment by philosofonusus** [comment]
If you still have this error then check your imports. I have had:
import {Link} from "react-router-dom";
import {Redirect} from "react-router-dom/modules"

The right way is
import {Link, Redirect} from "react-router-dom";
