### ISSUE TITLE
Cannot resolve module 'fbjs/lib/warning'

### ISSUE THREAD

**Issue by guven8** [taion/react-router-scroll#36]
I'm trying to use this package, but I'm getting this error message on import

`webpack-dev-server.js:1 ./~/react-scrollchor/lib/animatescroll.js
Module not found: Error: Cannot resolve module 'fbjs/lib/warning'`

im running 
`node v4.4.5`
`react: 15.2.0`,
`react-router: 2.4.1`,
`webpack: 1.12.9`
`webpack-dev-server: 1.14.0`

**Comment by taion** [comment]
That's not this library.
