### ISSUE TITLE
Don't scroll on navigate to same page

### ISSUE THREAD

**Issue by arasmussen** [taion/react-router-scroll#38]
If I'm on /foo and I click on a `<Link to="/foo" />`, it shouldn't scroll to the top of the page, yeah?

**Comment by taion** [comment]
You can use the `shouldUpdateScroll` hook to control this.

**Comment by arasmussen** [comment]
Thanks for the quick response. What are your thoughts on this being default behavior?

**Comment by taion** [comment]
No. That's not the behavior with a normal link.
