### ISSUE TITLE
Question: going to previous scroll position with ASYNC data

### ISSUE THREAD

**Issue by grossmail1** [taion/react-router-scroll#39]
Is there anything that I can do that will force this library to wait until async data/images have loaded before trying to go to a previous scroll-position when hitting the back button.  Currently if I have a previous page full of images who's data is getting pulled from an async request I just stay at the top of the page because the previous position doesn't exist when the page loads.

**Comment by taion** [comment]
Not out-of-the-box. Take a look at how this library uses the underlying `scroll-behavior` though.
