### ISSUE TITLE
Using react-router-scroll with react-custom-scrollbars

### ISSUE THREAD

**Issue by Zephir77167** [taion/react-router-scroll#42]
Hello,

I've implemented the code in the documentation to apply scroll behavior on my router, but I'm using react-custom-scrollbars (https://github.com/malte-wessel/react-custom-scrollbars), therefore nothing happens...

Is there a way I could call window.scrollbar.scrollToTop() (my way of scrolling to the top with my custom scrollbar) when useScroll normally scrolls?

Thanks in advance.

**Comment by taion** [comment]
The code to handle the actual scrolling is in scroll-behavior. I'd consider a PR there that customizes how that library does the actual scrolling.
