### ISSUE TITLE
How to apply `ignoreScrollBehavior` to Links instead of routes

### ISSUE THREAD

**Issue by tiemevanveen** [taion/react-router-scroll#43]
I want to have control over the scroll behavior on Link level because sometimes I want the same route to scroll and sometimes I don't.

Some time ago this worked just fine, but apperently it doesn't any more. 

```
// somewhere in a render method of some component
<Link to={{ pathname: '/some/path', state: { ignoreScrollBehavior: true } }}>
  My link
</Link>

// In my root component
<Router
  history={browserHistory}
  routes={routes}
  render={applyRouterMiddleware(useScroll(
    (prevRouterProps, { routes }) => !routes.some(
      route =>
        route.ignoreScrollBehavior ||
        (location.state && location.state.ignoreScrollBehavior)
    )
  ))}
/>
```

Do you have any advice in this case? I just want to scroll the window, so can't use `shouldUpdateScroll` right?

Great addition to the router, thanks btw 🎉 !

**Comment by taion** [comment]
Using `state.ignoreScrollBehavior` should work fine – probably you also want to check `location.action === 'PUSH'`.

If you want to scroll to a specific location, per the docs, you can return the location to which you want to scroll.

**Comment by tiemevanveen** [comment]
Yeah I thought so, but I get a undefined `location.state`. I'll look into it further later.

Thanks for the quick support.

**Comment by tiemevanveen** [comment]
Got it :/ Forgot to add the `location` variable in the destructuring.. stupid. 

```diff
// In my root component
<Router
  history={browserHistory}
  routes={routes}
  render={applyRouterMiddleware(useScroll(
-    (prevRouterProps, { routes }) => !routes.some(
+    (prevRouterProps, { routes, location }) => !routes.some(
      route =>
      route.ignoreScrollBehavior ||
      (location.state && location.state.ignoreScrollBehavior)
    )
  ))}
/>
```
