### ISSUE TITLE
Flickers

### ISSUE THREAD

**Issue by nycoliver** [taion/react-router-scroll#44]
Using exactly as described in the readme. On navigation there is a subtle flicker on the top of the page, about 400px. Makes this unusable for me! Appears in safari and chrome, didn't test in firefox. Recorded my screen to make sure I wasn't imagining.

**Comment by taion** [comment]
Do you have a repro?

**Comment by nycoliver** [comment]
I see, the problem is the page scrolls to the top before navigating to the next route. Happens so fast it looks like a flicker. Maybe I configured wrong?

```jsx
ReactDOM.render(
  <Router history={browserHistory} render={applyRouterMiddleware(useScroll())}>
    <Route path="/" component={App}>
      <IndexRoute component={Feed} />
      <Route path="/@:id" component={Profile} />
      <Route path="/p/:hash" component={Post} />
    </Route>
  </Router>,
  document.getElementById('root')
);
```

**Comment by taion** [comment]
Are you doing async data fetching in your route components? The scroll update happens in `componentDidUpdate` after the components render. You can also try forcing a reflow.

**Comment by nijynot** [comment]
I am async data fetching and have the same problem.

**Comment by taion** [comment]
With async data fetching this would be expected – the scroll update happens when the router finishes; it has no way to know about your async data dependencies.

**Comment by taion** [comment]
I can't do anything here without a repro.
