### ISSUE TITLE
Can't resolve 'history/lib/DOMStateStorage' after update

### ISSUE THREAD

**Issue by anaibol** [taion/react-router-scroll#51]
Hi! I just updated and I am receiving this error:

`./~/react-router-scroll/lib/StateStorage.js
Module not found: Error: Can't resolve 'history/lib/DOMStateStorage' in '/home/anaibol/Workspace/fr/node_modules/react-router-scroll/lib'
resolve 'history/lib/DOMStateStorage' in '/home/anaibol/Workspace/fr/node_modules/react-router-scroll/lib'
  Parsed request is a module
  using description file: /home/anaibol/Workspace/fr/node_modules/react-router-scroll/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /home/anaibol/Workspace/fr/node_modules/react-router-scroll/package.json (relative path: ./lib)
    resolve as module
`

**Comment by anaibol** [comment]
Sorry, the issue was caused by using a newer version of `history`.

**Comment by kmartinezmedia** [comment]
@anaibol does this mean we should downgrade history version to use this?

**Comment by jeremy-myRise-house** [comment]
@kmartinezmedia further to what @anaibol stated, I noticed the following in the my npm logs ;
`npm WARN react-router-scroll@0.4.1 requires a peer of history@^2.0.0 || ^3.0.0 but none was installed.`
I changed the history version in my package.json to ^3.0.0 and this corrected error.

**Comment by greateidea** [comment]
react-router-scroll@0.4.4 requires a peer of react-router@^2.3.0 || ^3.0.0
react-router@3.0.5 requires a peer of react@^0.14.0 || ^15.0.0
So I can't upgrade react to 16+ version?

**Comment by taion** [comment]
No, you just need to upgrade your React Router to the latest v3 release.

**Comment by ltsharma** [comment]
Still this issue persists, cannot use useScroll with "history": "^4.7.2" & "react-router": "^4.3.1". Tryied downgrading history to 3 then history error comes up.
