### ISSUE TITLE
Manage async transitions

### ISSUE THREAD

**Issue by dlmr** [taion/react-router-scroll#56]
Hello!

I'm trying to get this library work with a React Router middleware, [react-router-redial](https://github.com/dlmr/react-router-redial), that fetches data and delays rendering of the new `renderProps` until all async work has been completed. _Similar in concept to [`async-props`](https://github.com/ryanflorence/async-props)._

 I know that this is something this lib does not manage today as described in #44.
> With async data fetching this would be expected – the scroll update happens when the router finishes; it has no way to know about your async data dependencies

My question is what a recommended strategy here would be if one wants and needs to mange this. After reading through `scroll-behavior` I understand it as this type of logic should not be in that repo, given that async functionality was added and then removed. 

This can be managed in the projects current form by either using the `shouldUpdateScroll` and `this.updateScroll ` in project land or by using `this.context.scrollBehavior.scrollBehavior.updateScroll` in the middleware that wants to support `react-router-scroll`.  _Maybe there is some other ways as well?_

Is this the recommended way of doing this, by manage this outside of this lib, or is it something that could be added to this lib to make this easier and better?

**Comment by taion** [comment]
Use `scroll-behavior` directly. Create your own `ScrollBehavior` object, then call `updateScroll` on it when you need to.

Or take a look at Found, which moves that sort of data loading into the router itself and naturally avoids this split.
