### ISSUE TITLE
about example

### ISSUE THREAD

**Issue by highmind** [taion/react-router-scroll#57]
Can you show  a few examples?I'm still wondering about the function of it. thank you.

**Comment by taion** [comment]
There's nothing to show – it just makes the page scroll behavior mimic the browser.

**Comment by Maxhodges** [comment]
an implementation example would be helpful. I have no idea where to put your snippet.

**Comment by johncmunson** [comment]
> There's nothing to show

then this library shouldn't exist.

> it just makes the page scroll behavior mimic the browser

Okay, cool. I presume this is desirable, but I would first have to know the ways in which react-router deviates from convention.

I guess I'll have to do some experiments on my own to figure out what the value-added is here. You could save your users the trouble by creating some examples on codepen and adding more details to the readme.

**Comment by taion** [comment]
I mean, the thought is sort of – if you're using React Router, it should be immediately obvious that React Router doesn't do any scroll management out-of-the-box, and that you need something to mimic the browser's behavior.
