### ISSUE TITLE
StateStorage fails if sessionStorage is not available

### ISSUE THREAD

**Issue by andi5** [taion/react-router-scroll#60]
Since switching to react-router-scroll, we see the following error logs in our systems.

> Uncaught SecurityError: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
> SecurityError (DOM Exception 18): The operation is insecure. (?)

I think this is related to the private mode of some browsers, but I could not reproduce the problem.
My suspicion is that StateStorage should handle errors somehow and fall back to memory or other solutions if sessionStorage does not allow access.

**Comment by taion** [comment]
This is upstream in history

**Comment by andi5** [comment]
I created https://github.com/mjackson/history/issues/397 , hopefully they will do something with it.
