### ISSUE TITLE
Triggering a scroll to top after requests have finished for the next route

### ISSUE THREAD

**Issue by kellyrmilligan** [taion/react-router-scroll#61]
The ux I am wanting to achieve is to show a loading indicator over the current route contents while kicking off the data fetching for the next route. I have a component in my tree that when it receives new props, it does this, it blocks the new children from rendering until requests are finished. however, the page scrolls to the top first. if I return false from the callback `shouldUpdateScroll`, is it possible to then update the scroll later on?

**Comment by taion** [comment]
Not really. See discussion in https://github.com/taion/react-router-scroll/pull/59.

**Comment by kellyrmilligan** [comment]
thanks for the link, sorry I did't see that earlier. one idea i'm going to toy around with is what if shouldUpdateScroll returned a promise? could it just update the scroll when that promise was resolved?

**Comment by kellyrmilligan** [comment]
definitely will take a look. I think we're after the same idea.

**Comment by kellyrmilligan** [comment]
@taion one question, here's what I first tried. I noticed that scrollbehavior is on the context, so I tried this out. 

```js
function shouldUpdateScroll (prevRouterProps, currentRouterProps) {
  return !store.getState().isAppFetching.isAppFetching
}
```
then in a component that's preventing the new children from RR from rendering, when data requests are complete, I call 

```js
this.context.scrollBehavior.scrollBehavior.updateScroll()
```

this causes the page to be at the top no matter what is happening. is it because the scroll state is already something different at that point in the flow?

**Comment by taion** [comment]
This is one of those caveats noted in #59. It really just doesn't work well with the way React Router is set up.

**Comment by kellyrmilligan** [comment]
I guess then found is your answer to this problem?  or basically let RR transition the way it wants to and just show a spinner with placeholder content I guess. 😢

**Comment by taion** [comment]
Well, take a look at @dlmr's library. But ultimately, yes, if you want good handling of "the user has clicked on the link, but the data haven't all loaded yet, so we're still showing the old view with some loading indicator, and the transition isn't really complete", then that concept probably ought to live in the router, and you're not going to have an easy time without it.
