### ISSUE TITLE
Breaks when using latest version of  history

### ISSUE THREAD

**Issue by ryanwild** [taion/react-router-scroll#64]
Hi I'm getting an exception:
```
ModuleNotFoundError: Module not found: Error: Cannot resolve module 'history/lib/DOMStateStorage' in node_modules/react-router-scroll/lib
```
When using the latest version of the history module `"history": "^4.5.1"`

**Comment by ryanwild** [comment]
ok to solve the problem I'm using:

 `<Router history={browserHistory} onUpdate={() => window.scrollTo(0, 0)}>`

**Comment by taion** [comment]
They're not intended to work together. Note the peer dependency errors you're certainly getting.

**Comment by ryanwild** [comment]
Thanks, I can see, I went through backlog of issues and realized that this question has been logged before, apologies for the repeat...
