### ISSUE TITLE
peerDependency of history not needed?

### ISSUE THREAD

**Issue by ntucker** [taion/react-router-scroll#67]
I noticed this library works without it and then I looked at the source and didn't even notice an import of it.

**Comment by taion** [comment]
https://github.com/taion/react-router-scroll/blob/v0.4.1/src/StateStorage.js#L1

**Comment by ntucker** [comment]
Why is the dependency version 3 and not 4 which has been out for a while?

**Comment by taion** [comment]
You can find the answer pretty easily in older issues. I suggest looking there.
