### ISSUE TITLE
Slight scroll once route resolves

### ISSUE THREAD

**Issue by mmahalwy** [taion/react-router-scroll#7]
See gif:
![image](https://cloud.githubusercontent.com/assets/3749095/15061591/037dc758-12ec-11e6-83e8-dcb6347009e4.png)

After transition there is a slight few pixel smooth scroll.

**Comment by mmahalwy** [comment]
hmm gif not worky.. see: http://recordit.co/ONDW8MYgeJ

**Comment by taion** [comment]
What specifically is happening there? Is it not scrolling all the way to the top on the first frame?

**Comment by mmahalwy** [comment]
Yes, and it compensates within the first half second to scroll all the way to the top. This happens when hitting back on browser too

**Comment by taion** [comment]
Do you have anything like a runnable repro for this? I haven't seen this come up myself.

**Comment by mmahalwy** [comment]
Fixed.

**Comment by mmahalwy** [comment]
Thank you @taion !

**Comment by taion** [comment]
Thanks. Which release fixed the issue for you?

**Comment by mmahalwy** [comment]
Not sure, this was a while back when I filed this.
