### ISSUE TITLE
Uncaught TypeError: Cannot read property 'registerElement' of undefined

### ISSUE THREAD

**Issue by crobinson42** [taion/react-router-scroll#71]
Just started seeing this error - any help is appreciated. If I remove the `<ScrollContainer />` wrapper around my component (shown below), it works normal. Any ideas what could be causing this?

The error:
<img width="1084" alt="screenshot 2017-03-20 21 51 07" src="https://cloud.githubusercontent.com/assets/5973579/24133123/b5e74682-0db7-11e7-8382-93f5b1138150.png">

My code:
<img width="706" alt="screenshot 2017-03-20 21 51 15" src="https://cloud.githubusercontent.com/assets/5973579/24133116/abd30eb0-0db7-11e7-8e5d-e78285f9af4a.png">

**Comment by taion** [comment]
you're not rendering with the correct context; make sure you're applying the router middleware correctly
