### ISSUE TITLE
Publish ES6 code to npm as well

### ISSUE THREAD

**Issue by neeharv** [taion/react-router-scroll#78]
Put it under "jsnext:main" in package.json so tree shaking works out of the box without having to do do an import from `/lib`. Happy to send a PR for this if it makes sense.

**Comment by taion** [comment]
If you want, sure. I don't think it's a huge deal – `<ScrollContainer>` is pretty small. I've stopped adding ES module builds because the tree-shaking in webpack 2 isn't that great. It'd be `module` anyway.

I don't intend on doing anything for this, but I'd be happy to look at a PR.
