### ISSUE TITLE
Scrolling is not working when page have AJAX calls

### ISSUE THREAD

**Issue by ptsurko** [taion/react-router-scroll#80]
Scrolling does not work when page have some AJAX requests which loads data for the page and that are initiated after route transitioned to. In this case scrolling cannot be done correctly before all data has been loaded and page height/width has been restored.

How do you handle such cases?

I assume something like [delayed-scroll-restoration-polyfill](https://github.com/brigade/delayed-scroll-restoration-polyfill) which tried to do scroll in timeout.

**Comment by taion** [comment]
I would construct the `ScrollBehavior` object and invoke it directly – e.g. have something like this library, but call `scrollBehavior.updateScroll` only once you know your data are available.
