### ISSUE TITLE
useScroll can work with projects using history 4+

### ISSUE THREAD

**Issue by tommilligan** [taion/react-router-scroll#81]
As in previous issues (#26, #28, #40, #41, #51, #64, #67, #69), I wanted to use `react-router-scroll` with `history@^4.0.0`.

I can confirm that it is possible to use `useScroll` in projects with an existing `history` version of 4+ by installing  `history@^2.1.2` as an direct dependency of `react-router-scroll`. See [this diff](https://github.com/taion/react-router-scroll/compare/master...tommilligan:history-dependency#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) - I can produce a neat PR if @taion is interested.

I have released the package **[react-router-scroll-internal-history](https://www.npmjs.com/package/react-router-scroll-internal-history)** for my app to use while this is discussed. This fork passes the existing test suite on Node 6+, Chrome and Firefox, and `useScroll` exhibits expected behaviour in my app which uses:

* history@^4.5.1
* react-router@^3.0.1
* react-dom@^15.4.2
* react@^15.4.2

Install tested with npm and yarn.

**Comment by taion** [comment]
Uhh, how exactly does it work? You can't plug this middleware into React Router v4.

**Comment by tommilligan** [comment]
I have not tested this with RR v4 - as stated the app I'm working on still uses RR v3 and React v15 (I don't have control of the other dependencies). This is a fix for those who have a higher history version only.

**Comment by taion** [comment]
RRv4 does not use and in fact is not compatible with history v4: https://github.com/ReactTraining/react-router/blob/v3.0.5/package.json#L37

If you've somehow ended up with history v4 and RR v4, then something has gone wrong on your end.

**Comment by taion** [comment]
RRv3* rather

**Comment by tommilligan** [comment]
Thanks - have investigated and turns out the RRv4 is extraneous and not actually being used anywhere. As you correctly point out, RRv3 installs it's own dependency of history 3 to avoid conflict, so uninstalling history 4 as an app dependency and rerunning the install would solve this issue.

I'd still contest that the fewer peerDependencies the better, as to me it seems history is not being used in a peerDependency manner, but happy to close. Thanks for the help!

**Comment by taion** [comment]
It's used as a peer dependency because this is meant to support both RRv2 and RRv3. The two of those both (generally) pull in their own version of `history`, but respectively v2 and v3, and we just want to use whichever one is installed already, rather than bloating client bundles by throwing in another copy of `history`.
