### ISSUE TITLE
browser-style scroll behavior not working with <Link>

### ISSUE THREAD

**Issue by checkhavoc** [taion/react-router-scroll#82]
When using react-router ```<Link></Link>``` to go back to a previous page, it ends up scrolling to the top of the previous page instead of the previous page's scrollX/scrollY positions.

I've tried using custom scroll behavior, but it seems like that since ```<Link>``` is setting ```action = 'PUSH'```, it completely disregards the previous page's scrollX/scrollY and just uses the scrollX/scrollY of the current page.

When using the "browser" back-button, everything appears to work correctly, as it goes back to the previous page's original scrollX/scrollY position.

```
// Custom Scroll Behavior
function shouldUpdateScroll({ routes }) {
  if (routes.some(route => route.ignoreScrollBehavior)) {
    return false; // Uses current pages scrollX/scrollY instead of going back to previous page scrollX/scrollY
  }
  return true;
}
```
I'm able to implement some logic that will let me store the previous page's x/y and I can return that in ```shouldUpdateScroll```, but is there a way to have useScroll work exactly how the browser style back-button works when implementing with react-router ```<Link></Link>```?

**Comment by taion** [comment]
You shouldn't be using a `<Link>` for that. That doesn't really even make sense. Just do like `history.goBack()` or the equivalent on click.
