### ISSUE TITLE
ScrollContainer does not save position on page reload

### ISSUE THREAD

**Issue by alexhisen** [taion/react-router-scroll#83]
Unlike window scroll where position is saved immediately upon scroll, element scroll position is only saved on next transition. As a result it is lost on page reload. This is different from how window behaves and is unexpected.

This can be easily fixed in scroll-behavior by adding on('scroll') in registerElement or ScrollContainer could do it.

Where would you prefer for this to be implemented?

**Comment by taion** [comment]
Huh. I never actually thought about scroll behavior on a hard refresh. It's cool that it "just works" for the window.

It'd be great to see a fix – the PR would go in scroll-behavior.

**Comment by alexhisen** [comment]
PR submitted - https://github.com/taion/scroll-behavior/pull/122

**Comment by taion** [comment]
Thanks! Let's track the issue there. I'll take a look soon, when I get a chance.
