### ISSUE TITLE
Invalid prop `children` of type `array` supplied to `ScrollContainer`, expected a single ReactElement.

### ISSUE THREAD

**Issue by jolic** [taion/react-router-scroll#88]
react-router-scroll throws this error when used with React ^=16 and the render method returns an array. See blog post [New render return types: fragments and strings](https://reactjs.org/blog/2017/09/26/react-v16.0.html#new-render-return-types-fragments-and-strings)

**Comment by jolic** [comment]
Please replace inside ScrollContainer.js:

```js
const propTypes = {
  scrollKey: PropTypes.string.isRequired,
  shouldUpdateScroll: PropTypes.func,
  children: PropTypes.element.isRequired,
};
children: _propTypes.oneOfType([
      _propTypes.arrayOf(_propTypes2.node),
      _propTypes.node,
      _propTypes.string
  ]).isRequired
```
with 

```js
const propTypes = {
  scrollKey: PropTypes.string.isRequired,
  shouldUpdateScroll: PropTypes.func,
  children: .oneOfType([
      PropTypes.arrayOf(PropTypes.node),
      PropTypes.node,
      PropTypes.string
  ]).isRequired
};
```

**Comment by taion** [comment]
`<ScrollContainer>` needs a single element as child. It doesn't make sense to take an array there, because it needs access to the supposedly unique DOM node for that child, so that it can track its scroll position.
