### ISSUE TITLE
Preserving scroll position on window

### ISSUE THREAD

**Issue by ezmiller** [taion/react-router-scroll#89]
I would like to force scroll position on the window to be preserved for all browsers.  In order to override this behavior, it seems to me that I need to get `shouldUpdateScroll` to return the `scrollY` value of `window` before the navigation occurs, but I'm not sure the best way to do that. At the time the `shouldUpateScroll` callback is called, the value of `window.scrollY` seems already to be the one set by the browser's default behavior, i.e. `0` (on Chrome at least). Can anyone provide advice on the correct approach here?

**Comment by ezmiller** [comment]
Two possibilities that I'm considering, one of which seems to work decently: Record the scroll position before the navigation event either on 1) the window object, or 2) a redux store. I'm not crazy about either of these options, however. It would be nice if the scroll position didn't need to become a kind of state variable...

**Comment by taion** [comment]
Return `false` from `shouldUpdateScroll`: https://github.com/taion/react-router-scroll#custom-scroll-behavior

**Comment by ezmiller** [comment]
Hmmm. So `false` should also override the browser's default so it does nothing? That didn't work for me.

Incidentally, it wasn't clear to me if "a falsy value to suppress updating the scroll position" meant that the browser default would be overridden.

**Comment by taion** [comment]
`false` means "don't do anything". There should be no browser default in any event, since you're not actually doing any navigation.

**Comment by ezmiller** [comment]
@taion: I'm wondering if then I've misdiagnosed my problem. Can you explain why you say that there's no navigation? My understanding was that this whole middleware solution comes into play only when there is navigation, i.e. a route is being re-rendered, and that when navigation occurs the default of the browsers is to scroll to the top of the page... Is this incorrect?

**Comment by taion** [comment]
Without this middleware, the scroll position will not update at all when you click on a link.

When you hit the back or forward buttons, the browser may do something that may or may not be what you want.

**Comment by ezmiller** [comment]
Okay, in that case I think the repositioning must be caused by something else. Perhaps some interim step is removing big parts of the DOM causing the page to bump the scroll position. Thanks.
