### ISSUE TITLE
More usecases

### ISSUE THREAD

**Issue by volkanunsal** [taion/react-router-scroll#9]
I think this library might be helpful to me, but I'm not sure. My use case is that when I refresh a page which has dynamic content, the scroller goes back to the top of the page and doesn't go back to its original position when the content is loaded. Is this something I can address with this library or would I need something else?

**Comment by taion** [comment]
It depends how you load your dynamic content. This library triggers the scroll update on the completion of the router transition. If you need to trigger it at a different time, look at how I use the underlying `ScrollBehavior` object – I'll possibly eventually adapt this to work w/e.g. Relay lifecycle load.

**Comment by neutraali** [comment]
I think this issue should be renamed as "Support for dynamic content" or similarly - Right now it's a bit misleading. Some concrete examples on how to use react-router-scroll with async content would be much appreciated. The "possible, eventual" inclusion of lifecycle hooks of some sort would be even better. Right now there's not enough on the plate.
