### ISSUE TITLE
if use react dangerouslySetInnerHTML,scrollRestoration can not work

### ISSUE THREAD

**Issue by zhangolve** [taion/react-router-scroll#90]
In my project index page , I used dangerouslySetInnerHTML,but it can not work very well .when return to index page ,the position of the page always be top.

I had scanned the code.And when I delete some code in ScrollContext component as below,everything works fine.

   //if (location === prevLocation) {
    //  return;
    //}

I found scrollBehavior.updateScroll in ScrollContext constructor ,could I remove it from the constructor ?

**Comment by taion** [comment]
The initial scroll update is so the page will scroll appropriately on initial load, if it's a pop from outside the SPA.

**Comment by zhangolve** [comment]
Sorry,you didn't answer my question.
If I want to use this module and want to usedangerouslySetInnerHTML ,what should I do if your module is no problem?
