### ISSUE TITLE
Delay for page transition

### ISSUE THREAD

**Issue by b0gd4n** [taion/react-router-scroll#93]
Hey there.

Using a fork of this on a Gatsby project, which has page transitions.
I noticed that, on route change, the page scrolls to top, just before the fade out transition of the existing page begins. Is there a way to add a delay to the scroll, enough for the fade out to happen, then scroll to top, then fade in the new page?

**Comment by taion** [comment]
I'm not sure how you'd do this with Gatsby specifically, but more generally, see the section of the docs starting

>You can customize `useScroll` even further
